### ISSUE TITLE
Typo and markdown backticks

### ISSUE THREAD

**Issue by andreyrcdias** [JessicaNathany/the-office.api#2]
Hello, congratulations on the work!!!

I would like to suggest two improvements here.

1. Fix the typo in the infra module: `insfrastructure` -> `infrastructure`
2. What about adding [backticks](https://www.markdownguide.org/basic-syntax#code) to the API routes, I believe it makes it more readable, for example:
    - `GET /characters` - retrieves a list of all characters in The Office.
    - `GET /characters/{id}` - retrieves a specific character by ID.
    - `GET /episodes` - retrieves a list of all episodes in The Office.
    - `GET /episodes/{id}` - retrieves a specific episode by ID.
    - `GET /quotes/characters/{id}` - retrieves a list of all better phrases for specific characters in The Office.

I don't have the setup for C# so I didn't fork and make the changes

**Comment by JessicaNathany** [comment]
Oh, thanks man! I will change here, I have other changes in develop that I need to merge too. But I will open its issue, for change the readme here. 

:)

**Comment by JessicaNathany** [comment]
@andreyrcdias the first I don't understand very well, Fix 1
